language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - os: osx
      env: TYPE=MacOS

    # - os: linux
    #   env: TYPE=ubuntu-16.04

    # - os: linux
    #   env: TYPE=ubuntu-17.10

    - os: linux
      env: TYPE=ubuntu-18.04

    # - os: linux
    #   env: TYPE=debian-buster

before_install:
  - source ./.ci/update-docker.sh


install:
  - source ./.ci/install-deps.sh
  
script:
  - bash ./.ci/run-tests.sh
