open Ctypes

val c_ALLOCATOR_SYSMEM : string
(* TODO : constant BUFFER_COPY_ALL type not implemented for interface *)(* TODO : constant BUFFER_COPY_ALL type not implemented for interface *)(* TODO : constant BUFFER_COPY_METADATA type not implemented for interface *)(* TODO : constant BUFFER_COPY_METADATA type not implemented for interface *)val c_BUFFER_OFFSET_NONE : Unsigned.uint64
val c_CAN_INLINE : int32
val c_CAPS_FEATURE_MEMORY_SYSTEM_MEMORY : string
val c_CLOCK_TIME_NONE : Unsigned.uint64
val c_DEBUG_BG_MASK : int32
val c_DEBUG_FG_MASK : int32
val c_DEBUG_FORMAT_MASK : int32
val c_ELEMENT_FACTORY_KLASS_DECODER : string
val c_ELEMENT_FACTORY_KLASS_DECRYPTOR : string
val c_ELEMENT_FACTORY_KLASS_DEMUXER : string
val c_ELEMENT_FACTORY_KLASS_DEPAYLOADER : string
val c_ELEMENT_FACTORY_KLASS_ENCODER : string
val c_ELEMENT_FACTORY_KLASS_ENCRYPTOR : string
val c_ELEMENT_FACTORY_KLASS_FORMATTER : string
val c_ELEMENT_FACTORY_KLASS_HARDWARE : string
val c_ELEMENT_FACTORY_KLASS_MEDIA_AUDIO : string
val c_ELEMENT_FACTORY_KLASS_MEDIA_IMAGE : string
val c_ELEMENT_FACTORY_KLASS_MEDIA_METADATA : string
val c_ELEMENT_FACTORY_KLASS_MEDIA_SUBTITLE : string
val c_ELEMENT_FACTORY_KLASS_MEDIA_VIDEO : string
val c_ELEMENT_FACTORY_KLASS_MUXER : string
val c_ELEMENT_FACTORY_KLASS_PARSER : string
val c_ELEMENT_FACTORY_KLASS_PAYLOADER : string
val c_ELEMENT_FACTORY_KLASS_SINK : string
val c_ELEMENT_FACTORY_KLASS_SRC : string
val c_ELEMENT_FACTORY_TYPE_ANY : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_AUDIOVIDEO_SINKS : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_AUDIO_ENCODER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_DECODABLE : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_DECODER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_DECRYPTOR : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_DEMUXER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_DEPAYLOADER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_ENCODER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_ENCRYPTOR : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_FORMATTER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MAX_ELEMENTS : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_ANY : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_AUDIO : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_IMAGE : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_METADATA : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_SUBTITLE : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MEDIA_VIDEO : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_MUXER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_PARSER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_PAYLOADER : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_SINK : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_SRC : Unsigned.uint64
val c_ELEMENT_FACTORY_TYPE_VIDEO_ENCODER : Unsigned.uint64
val c_ELEMENT_METADATA_AUTHOR : string
val c_ELEMENT_METADATA_DESCRIPTION : string
val c_ELEMENT_METADATA_DOC_URI : string
val c_ELEMENT_METADATA_ICON_NAME : string
val c_ELEMENT_METADATA_KLASS : string
val c_ELEMENT_METADATA_LONGNAME : string
val c_EVENT_NUM_SHIFT : int32
(* TODO : constant EVENT_TYPE_BOTH type not implemented for interface *)(* TODO : constant EVENT_TYPE_BOTH type not implemented for interface *)val c_FLAG_SET_MASK_EXACT : Unsigned.uint32
val c_FORMAT_PERCENT_MAX : int64
val c_FORMAT_PERCENT_SCALE : int64
val c_GROUP_ID_INVALID : int32
val c_LICENSE_UNKNOWN : string
(* TODO : constant LOCK_FLAG_READWRITE type not implemented for interface *)(* TODO : constant LOCK_FLAG_READWRITE type not implemented for interface *)(* TODO : constant MAP_READWRITE type not implemented for interface *)(* TODO : constant MAP_READWRITE type not implemented for interface *)val c_META_TAG_MEMORY_STR : string
val c_MSECOND : int64
val c_NSECOND : int64
val c_PARAM_CONTROLLABLE : int32
val c_PARAM_MUTABLE_PAUSED : int32
val c_PARAM_MUTABLE_PLAYING : int32
val c_PARAM_MUTABLE_READY : int32
val c_PARAM_USER_SHIFT : int32
val c_PROTECTION_SYSTEM_ID_CAPS_FIELD : string
val c_PROTECTION_UNSPECIFIED_SYSTEM_ID : string
val c_QUERY_NUM_SHIFT : int32
(* TODO : constant QUERY_TYPE_BOTH type not implemented for interface *)(* TODO : constant QUERY_TYPE_BOTH type not implemented for interface *)val c_SECOND : int64
val c_SEQNUM_INVALID : int32
val c_TAG_ALBUM : string
val c_TAG_ALBUM_ARTIST : string
val c_TAG_ALBUM_ARTIST_SORTNAME : string
val c_TAG_ALBUM_GAIN : string
val c_TAG_ALBUM_PEAK : string
val c_TAG_ALBUM_SORTNAME : string
val c_TAG_ALBUM_VOLUME_COUNT : string
val c_TAG_ALBUM_VOLUME_NUMBER : string
val c_TAG_APPLICATION_DATA : string
val c_TAG_APPLICATION_NAME : string
val c_TAG_ARTIST : string
val c_TAG_ARTIST_SORTNAME : string
val c_TAG_ATTACHMENT : string
val c_TAG_AUDIO_CODEC : string
val c_TAG_BEATS_PER_MINUTE : string
val c_TAG_BITRATE : string
val c_TAG_CODEC : string
val c_TAG_COMMENT : string
val c_TAG_COMPOSER : string
val c_TAG_COMPOSER_SORTNAME : string
val c_TAG_CONDUCTOR : string
val c_TAG_CONTACT : string
val c_TAG_CONTAINER_FORMAT : string
val c_TAG_COPYRIGHT : string
val c_TAG_COPYRIGHT_URI : string
val c_TAG_DATE : string
val c_TAG_DATE_TIME : string
val c_TAG_DESCRIPTION : string
val c_TAG_DEVICE_MANUFACTURER : string
val c_TAG_DEVICE_MODEL : string
val c_TAG_DURATION : string
val c_TAG_ENCODED_BY : string
val c_TAG_ENCODER : string
val c_TAG_ENCODER_VERSION : string
val c_TAG_EXTENDED_COMMENT : string
val c_TAG_GENRE : string
val c_TAG_GEO_LOCATION_CAPTURE_DIRECTION : string
val c_TAG_GEO_LOCATION_CITY : string
val c_TAG_GEO_LOCATION_COUNTRY : string
val c_TAG_GEO_LOCATION_ELEVATION : string
val c_TAG_GEO_LOCATION_HORIZONTAL_ERROR : string
val c_TAG_GEO_LOCATION_LATITUDE : string
val c_TAG_GEO_LOCATION_LONGITUDE : string
val c_TAG_GEO_LOCATION_MOVEMENT_DIRECTION : string
val c_TAG_GEO_LOCATION_MOVEMENT_SPEED : string
val c_TAG_GEO_LOCATION_NAME : string
val c_TAG_GEO_LOCATION_SUBLOCATION : string
val c_TAG_GROUPING : string
val c_TAG_HOMEPAGE : string
val c_TAG_IMAGE : string
val c_TAG_IMAGE_ORIENTATION : string
val c_TAG_INTERPRETED_BY : string
val c_TAG_ISRC : string
val c_TAG_KEYWORDS : string
val c_TAG_LANGUAGE_CODE : string
val c_TAG_LANGUAGE_NAME : string
val c_TAG_LICENSE : string
val c_TAG_LICENSE_URI : string
val c_TAG_LOCATION : string
val c_TAG_LYRICS : string
val c_TAG_MAXIMUM_BITRATE : string
val c_TAG_MIDI_BASE_NOTE : string
val c_TAG_MINIMUM_BITRATE : string
val c_TAG_NOMINAL_BITRATE : string
val c_TAG_ORGANIZATION : string
val c_TAG_PERFORMER : string
val c_TAG_PREVIEW_IMAGE : string
val c_TAG_PRIVATE_DATA : string
val c_TAG_PUBLISHER : string
val c_TAG_REFERENCE_LEVEL : string
val c_TAG_SERIAL : string
val c_TAG_SHOW_EPISODE_NUMBER : string
val c_TAG_SHOW_NAME : string
val c_TAG_SHOW_SEASON_NUMBER : string
val c_TAG_SHOW_SORTNAME : string
val c_TAG_SUBTITLE_CODEC : string
val c_TAG_TITLE : string
val c_TAG_TITLE_SORTNAME : string
val c_TAG_TRACK_COUNT : string
val c_TAG_TRACK_GAIN : string
val c_TAG_TRACK_NUMBER : string
val c_TAG_TRACK_PEAK : string
val c_TAG_USER_RATING : string
val c_TAG_VERSION : string
val c_TAG_VIDEO_CODEC : string
val c_TOC_REPEAT_COUNT_INFINITE : int32
val c_URI_NO_PORT : int32
val c_USECOND : int64
val c_VALUE_EQUAL : int32
val c_VALUE_GREATER_THAN : int32
val c_VALUE_LESS_THAN : int32
val c_VALUE_UNORDERED : int32
val c_VERSION_MAJOR : int32
val c_VERSION_MICRO : int32
val c_VERSION_MINOR : int32
val c_VERSION_NANO : int32
(*DEPRECATED : uri_construct*)
val is_initialized :
  unit -> bool

