open Ctypes
open Foreign

let c_ALLOCATOR_SYSMEM = "SystemMemory"
let c_BUFFER_OFFSET_NONE = Unsigned.UInt64.of_string "18446744073709551615"
let c_CAN_INLINE = 1l
let c_CAPS_FEATURE_MEMORY_SYSTEM_MEMORY = "memory:SystemMemory"
let c_CLOCK_TIME_NONE = Unsigned.UInt64.of_string "18446744073709551615"
let c_DEBUG_BG_MASK = 240l
let c_DEBUG_FG_MASK = 15l
let c_DEBUG_FORMAT_MASK = 65280l
let c_ELEMENT_FACTORY_KLASS_DECODER = "Decoder"
let c_ELEMENT_FACTORY_KLASS_DECRYPTOR = "Decryptor"
let c_ELEMENT_FACTORY_KLASS_DEMUXER = "Demuxer"
let c_ELEMENT_FACTORY_KLASS_DEPAYLOADER = "Depayloader"
let c_ELEMENT_FACTORY_KLASS_ENCODER = "Encoder"
let c_ELEMENT_FACTORY_KLASS_ENCRYPTOR = "Encryptor"
let c_ELEMENT_FACTORY_KLASS_FORMATTER = "Formatter"
let c_ELEMENT_FACTORY_KLASS_HARDWARE = "Hardware"
let c_ELEMENT_FACTORY_KLASS_MEDIA_AUDIO = "Audio"
let c_ELEMENT_FACTORY_KLASS_MEDIA_IMAGE = "Image"
let c_ELEMENT_FACTORY_KLASS_MEDIA_METADATA = "Metadata"
let c_ELEMENT_FACTORY_KLASS_MEDIA_SUBTITLE = "Subtitle"
let c_ELEMENT_FACTORY_KLASS_MEDIA_VIDEO = "Video"
let c_ELEMENT_FACTORY_KLASS_MUXER = "Muxer"
let c_ELEMENT_FACTORY_KLASS_PARSER = "Parser"
let c_ELEMENT_FACTORY_KLASS_PAYLOADER = "Payloader"
let c_ELEMENT_FACTORY_KLASS_SINK = "Sink"
let c_ELEMENT_FACTORY_KLASS_SRC = "Source"
let c_ELEMENT_FACTORY_TYPE_ANY = Unsigned.UInt64.of_string "562949953421311"
let c_ELEMENT_FACTORY_TYPE_AUDIOVIDEO_SINKS = Unsigned.UInt64.of_string "3940649673949188"
let c_ELEMENT_FACTORY_TYPE_AUDIO_ENCODER = Unsigned.UInt64.of_string "1125899906842626"
let c_ELEMENT_FACTORY_TYPE_DECODABLE = Unsigned.UInt64.of_string "1377"
let c_ELEMENT_FACTORY_TYPE_DECODER = Unsigned.UInt64.of_string "1"
let c_ELEMENT_FACTORY_TYPE_DECRYPTOR = Unsigned.UInt64.of_string "1024"
let c_ELEMENT_FACTORY_TYPE_DEMUXER = Unsigned.UInt64.of_string "32"
let c_ELEMENT_FACTORY_TYPE_DEPAYLOADER = Unsigned.UInt64.of_string "256"
let c_ELEMENT_FACTORY_TYPE_ENCODER = Unsigned.UInt64.of_string "2"
let c_ELEMENT_FACTORY_TYPE_ENCRYPTOR = Unsigned.UInt64.of_string "2048"
let c_ELEMENT_FACTORY_TYPE_FORMATTER = Unsigned.UInt64.of_string "512"
let c_ELEMENT_FACTORY_TYPE_MAX_ELEMENTS = Unsigned.UInt64.of_string "281474976710656"
let c_ELEMENT_FACTORY_TYPE_MEDIA_ANY = Unsigned.UInt64.of_string "18446462598732840960"
let c_ELEMENT_FACTORY_TYPE_MEDIA_AUDIO = Unsigned.UInt64.of_string "1125899906842624"
let c_ELEMENT_FACTORY_TYPE_MEDIA_IMAGE = Unsigned.UInt64.of_string "2251799813685248"
let c_ELEMENT_FACTORY_TYPE_MEDIA_METADATA = Unsigned.UInt64.of_string "9007199254740992"
let c_ELEMENT_FACTORY_TYPE_MEDIA_SUBTITLE = Unsigned.UInt64.of_string "4503599627370496"
let c_ELEMENT_FACTORY_TYPE_MEDIA_VIDEO = Unsigned.UInt64.of_string "562949953421312"
let c_ELEMENT_FACTORY_TYPE_MUXER = Unsigned.UInt64.of_string "16"
let c_ELEMENT_FACTORY_TYPE_PARSER = Unsigned.UInt64.of_string "64"
let c_ELEMENT_FACTORY_TYPE_PAYLOADER = Unsigned.UInt64.of_string "128"
let c_ELEMENT_FACTORY_TYPE_SINK = Unsigned.UInt64.of_string "4"
let c_ELEMENT_FACTORY_TYPE_SRC = Unsigned.UInt64.of_string "8"
let c_ELEMENT_FACTORY_TYPE_VIDEO_ENCODER = Unsigned.UInt64.of_string "2814749767106562"
let c_ELEMENT_METADATA_AUTHOR = "author"
let c_ELEMENT_METADATA_DESCRIPTION = "description"
let c_ELEMENT_METADATA_DOC_URI = "doc-uri"
let c_ELEMENT_METADATA_ICON_NAME = "icon-name"
let c_ELEMENT_METADATA_KLASS = "klass"
let c_ELEMENT_METADATA_LONGNAME = "long-name"
let c_EVENT_NUM_SHIFT = 8l
let c_FLAG_SET_MASK_EXACT = Unsigned.UInt32.of_string "4294967295"
let c_FORMAT_PERCENT_MAX = 1000000L
let c_FORMAT_PERCENT_SCALE = 10000L
let c_GROUP_ID_INVALID = 0l
let c_LICENSE_UNKNOWN = "unknown"
let c_META_TAG_MEMORY_STR = "memory"
let c_MSECOND = 1000000L
let c_NSECOND = 1L
let c_PARAM_CONTROLLABLE = 512l
let c_PARAM_MUTABLE_PAUSED = 2048l
let c_PARAM_MUTABLE_PLAYING = 4096l
let c_PARAM_MUTABLE_READY = 1024l
let c_PARAM_USER_SHIFT = 65536l
let c_PROTECTION_SYSTEM_ID_CAPS_FIELD = "protection-system"
let c_PROTECTION_UNSPECIFIED_SYSTEM_ID = "unspecified-system-id"
let c_QUERY_NUM_SHIFT = 8l
let c_SECOND = 1000000000L
let c_SEQNUM_INVALID = 0l
let c_TAG_ALBUM = "album"
let c_TAG_ALBUM_ARTIST = "album-artist"
let c_TAG_ALBUM_ARTIST_SORTNAME = "album-artist-sortname"
let c_TAG_ALBUM_GAIN = "replaygain-album-gain"
let c_TAG_ALBUM_PEAK = "replaygain-album-peak"
let c_TAG_ALBUM_SORTNAME = "album-sortname"
let c_TAG_ALBUM_VOLUME_COUNT = "album-disc-count"
let c_TAG_ALBUM_VOLUME_NUMBER = "album-disc-number"
let c_TAG_APPLICATION_DATA = "application-data"
let c_TAG_APPLICATION_NAME = "application-name"
let c_TAG_ARTIST = "artist"
let c_TAG_ARTIST_SORTNAME = "artist-sortname"
let c_TAG_ATTACHMENT = "attachment"
let c_TAG_AUDIO_CODEC = "audio-codec"
let c_TAG_BEATS_PER_MINUTE = "beats-per-minute"
let c_TAG_BITRATE = "bitrate"
let c_TAG_CODEC = "codec"
let c_TAG_COMMENT = "comment"
let c_TAG_COMPOSER = "composer"
let c_TAG_COMPOSER_SORTNAME = "composer-sortname"
let c_TAG_CONDUCTOR = "conductor"
let c_TAG_CONTACT = "contact"
let c_TAG_CONTAINER_FORMAT = "container-format"
let c_TAG_COPYRIGHT = "copyright"
let c_TAG_COPYRIGHT_URI = "copyright-uri"
let c_TAG_DATE = "date"
let c_TAG_DATE_TIME = "datetime"
let c_TAG_DESCRIPTION = "description"
let c_TAG_DEVICE_MANUFACTURER = "device-manufacturer"
let c_TAG_DEVICE_MODEL = "device-model"
let c_TAG_DURATION = "duration"
let c_TAG_ENCODED_BY = "encoded-by"
let c_TAG_ENCODER = "encoder"
let c_TAG_ENCODER_VERSION = "encoder-version"
let c_TAG_EXTENDED_COMMENT = "extended-comment"
let c_TAG_GENRE = "genre"
let c_TAG_GEO_LOCATION_CAPTURE_DIRECTION = "geo-location-capture-direction"
let c_TAG_GEO_LOCATION_CITY = "geo-location-city"
let c_TAG_GEO_LOCATION_COUNTRY = "geo-location-country"
let c_TAG_GEO_LOCATION_ELEVATION = "geo-location-elevation"
let c_TAG_GEO_LOCATION_HORIZONTAL_ERROR = "geo-location-horizontal-error"
let c_TAG_GEO_LOCATION_LATITUDE = "geo-location-latitude"
let c_TAG_GEO_LOCATION_LONGITUDE = "geo-location-longitude"
let c_TAG_GEO_LOCATION_MOVEMENT_DIRECTION = "geo-location-movement-direction"
let c_TAG_GEO_LOCATION_MOVEMENT_SPEED = "geo-location-movement-speed"
let c_TAG_GEO_LOCATION_NAME = "geo-location-name"
let c_TAG_GEO_LOCATION_SUBLOCATION = "geo-location-sublocation"
let c_TAG_GROUPING = "grouping"
let c_TAG_HOMEPAGE = "homepage"
let c_TAG_IMAGE = "image"
let c_TAG_IMAGE_ORIENTATION = "image-orientation"
let c_TAG_INTERPRETED_BY = "interpreted-by"
let c_TAG_ISRC = "isrc"
let c_TAG_KEYWORDS = "keywords"
let c_TAG_LANGUAGE_CODE = "language-code"
let c_TAG_LANGUAGE_NAME = "language-name"
let c_TAG_LICENSE = "license"
let c_TAG_LICENSE_URI = "license-uri"
let c_TAG_LOCATION = "location"
let c_TAG_LYRICS = "lyrics"
let c_TAG_MAXIMUM_BITRATE = "maximum-bitrate"
let c_TAG_MIDI_BASE_NOTE = "midi-base-note"
let c_TAG_MINIMUM_BITRATE = "minimum-bitrate"
let c_TAG_NOMINAL_BITRATE = "nominal-bitrate"
let c_TAG_ORGANIZATION = "organization"
let c_TAG_PERFORMER = "performer"
let c_TAG_PREVIEW_IMAGE = "preview-image"
let c_TAG_PRIVATE_DATA = "private-data"
let c_TAG_PUBLISHER = "publisher"
let c_TAG_REFERENCE_LEVEL = "replaygain-reference-level"
let c_TAG_SERIAL = "serial"
let c_TAG_SHOW_EPISODE_NUMBER = "show-episode-number"
let c_TAG_SHOW_NAME = "show-name"
let c_TAG_SHOW_SEASON_NUMBER = "show-season-number"
let c_TAG_SHOW_SORTNAME = "show-sortname"
let c_TAG_SUBTITLE_CODEC = "subtitle-codec"
let c_TAG_TITLE = "title"
let c_TAG_TITLE_SORTNAME = "title-sortname"
let c_TAG_TRACK_COUNT = "track-count"
let c_TAG_TRACK_GAIN = "replaygain-track-gain"
let c_TAG_TRACK_NUMBER = "track-number"
let c_TAG_TRACK_PEAK = "replaygain-track-peak"
let c_TAG_USER_RATING = "user-rating"
let c_TAG_VERSION = "version"
let c_TAG_VIDEO_CODEC = "video-codec"
let c_TOC_REPEAT_COUNT_INFINITE = -1l
let c_URI_NO_PORT = 0l
let c_USECOND = 1000L
let c_VALUE_EQUAL = 0l
let c_VALUE_GREATER_THAN = 1l
let c_VALUE_LESS_THAN = -1l
let c_VALUE_UNORDERED = 2l
let c_VERSION_MAJOR = 1l
let c_VERSION_MICRO = 0l
let c_VERSION_MINOR = 16l
let c_VERSION_NANO = 0l
(*DEPRECATED : uri_construct*)
let is_initialized =
  foreign "gst_is_initialized" (void @-> returning (bool))

